package io.github.cybersafetyid.buildlogic.api

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Regenerates the Bluetooth API compatibility matrix from the Android SDK `api-versions.xml`
 * database — the same data Android Lint uses to decide whether an API call is available on the
 * project's `minSdk`.
 *
 * The task lives in `build-logic` instead of the root build script because Gradle's Kotlin DSL
 * does not support declaring local classes inside task configuration lambdas.
 */
public abstract class GenerateCompatibilityMatrixTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    public abstract val apiVersionsXml: RegularFileProperty

    @get:OutputFile
    public abstract val outputFile: RegularFileProperty

    @get:Input
    public abstract val targetApiLevel: Property<Int>

    @TaskAction
    public fun generate() {
        val source = apiVersionsXml.get().asFile
        check(source.isFile) {
            "api-versions.xml was not found at ${source.absolutePath}. " +
                "Set ANDROID_HOME or install the matching Android platform."
        }

        val target = outputFile.get().asFile
        target.parentFile.mkdirs()
        target.writeText(renderMatrix(source.readText(), targetApiLevel.get()))
        logger.lifecycle("Wrote ${target.path}")
    }

    private class Member(val name: String, val since: String, val deprecated: Boolean) {
        fun majorVersion(): Int = since.substringBefore('.').toIntOrNull() ?: 0
    }

    private class PlatformClass(val name: String, val members: List<Member>)

    private fun renderMatrix(xml: String, targetApi: Int): String {
        val classRegex = Regex("""<class name="([^"]+)"([^>]*)>(.*?)</class>""", RegexOption.DOT_MATCHES_ALL)
        val memberRegex = Regex("""<(?:method|field) name="([^"]+)"([^>]*)/>""")
        val sinceRegex = Regex("""since="([^"]+)"""")
        val packages = listOf("android/bluetooth/", "android/bluetooth/le/", "android/ranging/")

        val classes = classRegex.findAll(xml).mapNotNull { classMatch ->
            val className = classMatch.groupValues[1]
            if (packages.none { className.startsWith(it) }) return@mapNotNull null

            val members = memberRegex.findAll(classMatch.groupValues[3]).mapNotNull { memberMatch ->
                val attrs = memberMatch.groupValues[2]
                val since = sinceRegex.find(attrs)?.groupValues?.get(1) ?: return@mapNotNull null
                Member(
                    name = memberMatch.groupValues[1],
                    since = since,
                    deprecated = "deprecated=" in attrs,
                )
            }.toList()

            PlatformClass(className.replace('/', '.'), members)
        }.sortedBy { it.name }.toList()

        return buildString {
            appendLine("# Bluetooth API compatibility matrix")
            appendLine()
            appendLine("> Generated by `./gradlew generateCompatibilityMatrix` from the Android SDK database")
            appendLine("> `platforms/android-$targetApi.0/data/api-versions.xml`. Never edit by hand —")
            appendLine("> re-run the task after bumping `compileSdk`.")
            appendLine()
            appendLine("`since` values use the platform notation: `37.0` is Android 17 and `36.1` is the")
            appendLine("16.1 QPR release, a *minor* SDK version handled through `SDK_INT_FULL`.")
            appendLine()

            for (apiLevel in 21..targetApi) {
                val entries = classes.mapNotNull { platformClass ->
                    val hits = platformClass.members.filter { it.majorVersion() == apiLevel }
                    if (hits.isEmpty()) null else platformClass.name to hits
                }
                if (entries.isEmpty()) continue

                appendLine("## Added in API $apiLevel")
                appendLine()
                for ((className, members) in entries) {
                    appendLine("### `$className`")
                    appendLine()
                    for (member in members.sortedBy { it.since }) {
                        val deprecation = if (member.deprecated) " _(deprecated)_" else ""
                        appendLine("- `${member.name}` — `since ${member.since}`$deprecation")
                    }
                    appendLine()
                }
            }
        }
    }
}
